sudo: false
language: cpp

before_script:
  - bash scripts/install_mpich.sh
cache:
  directories:
    - $HOME/mpich
    - $HOME/llvm-3.8.0
    - $HOME/llvm-3.7.1
    - $HOME/llvm-3.6.2
    - $HOME/llvm-3.5.2

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "linux"]; then
      if [ -n "${LLVM_VERSION}" ]; then
        if [ -z "$(ls -A llvm-${LLVM_VERSION})" ]; then
          wget -O llvm-${LLVM_VERSION}.tar.xz http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
          mkdir llvm-$LLVM_VERSION;
          xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
        fi;
        llvm-${LLVM_VERSION}/bin/llvm-config --version;
        export LLVM_CONFIG="${HOME}/llvm-${LLVM_VERSION}/bin/llvm-config";
        export PATH=${HOME}/llvm-${LLVM_VERSION}/bin:${PATH};
        export LD_LIBRARY_PATH=${HOME}/llvm-${LLVM_VERSION}/lib:${HOME}/llvm-${LLVM_VERSION}:$LD_LIBRARY_PATH;
      fi;
    fi;
      
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - gcc-4.9
            - g++-4.9
      env:
        COMPILER=g++-4.9
        LLVM_VERSION=
      
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - gcc-5
            - g++-5
      env:
        - COMPILER=g++-5
        - LLVM_VERSION=

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages:
            - gcc-6
            - g++-6
      env:
        - COMPILER=g++-6
        - LLVM_VERSION=

    # - os: linux
    #   compiler: clang
    #   env:
    #     - COMPILER=clang++
    #     - LLVM_VERSION=3.5.2

    # - os: linux
    #   compiler: clang
    #   env:
    #     - COMPILER=clang++
    #     - LLVM_VERSION=3.6.2

    # - os: linux
    #   compiler: clang
    #   env:
    #     - COMPILER=clang++
    #     - LLVM_VERSION=3.7.1

    # - os: linux
    #   compiler: clang
    #   env:
    #     - COMPILER=clang++
    #     - LLVM_VERSION=3.8.0

branches:
  only:
    - master
script:
  - export PATH=$HOME/mpich/bin:$PATH
  - export LD_LIBRARY_PATH=$HOME/mpich/lib:$LD_LIBRARY_PATH
  - env SCALE=s bash ./test.sh

notifications:
  slack: tapas-dev:OwLgVsyfrKZD1RVsI1b8hQkG
  on_failure: always
  on_success: never
